# Generated by Django 4.2.5 on 2023-09-24 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonstatus',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
